# Generated by Django 4.2.1 on 2023-06-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(default='Дайте описание', verbose_name='Описание')),
                ('start_time', models.DateField(default=datetime.date.today, verbose_name='Дата начала')),
                ('end_time', models.DateField(default=datetime.date.today, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('to-do', 'To-Do'), ('in progress', 'In Progress'), ('done', 'Done')], max_length=20)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
